version: '2'

services:
  notification-service:
    image: wiremock/wiremock:2.33.2
    ports:
      - "9090:9090"
    volumes:
      - "./wiremock:/home/wiremock"
    command: --verbose --port 9090

  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres

