spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
    drop-first: true

  flyway:
    enabled: false

cabas:
    notificationBaseUrl: http://localhost:9090